// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "./js/jquery-3.1.1.min.js"
import "./js/flickity.min.js"
import "./js/easypiechart.min.js"
import "./js/parallax.js"
import "./js/typed.min.js"
// import "./js/datepicker.js"
import "./js/isotope.min.js"
import "./js/ytplayer.min.js"
import "./js/lightbox.min.js"
import "./js/granim.min.js"
import "./js/jquery.steps.min.js"
import "./js/countdown.min.js"
import "./js/twitterfetcher.min.js"
import "./js/spectragram.min.js"
import "./js/smooth-scroll.min.js"
import "./js/scripts.js"
